### ISSUE TITLE
ディレクトリ構成の階層が一つ深いため修正する

### ISSUE THREAD

**Issue by arith-y-ono** [arith-y-ono/openId#10]
## ===== 期待する利益・回避したい不利益は？（Why）=====
https://github.com/arith-y-ono/openId/issues/1 参照

## ===== どうやって実現・解決する？（How） =====
ディレクトリ構成の階層が一つ深いため修正する

### 受け入れ基準（期待すること）
- [ ] リポジトリ直下にindex.jsがある

**Comment by arith-alexander** [comment]
https://github.com/arith-y-ono/openId/pull/11 にて対応済み
