### ISSUE TITLE
個人開発環境を作成する（小野）

### ISSUE THREAD

**Issue by arith-y-ono** [arith-y-ono/openId#3]
## ===== 期待する利益・回避したい不利益は？（Why）=====
https://github.com/arith-y-ono/openId/issues/1 参照

## ===== どうやって実現・解決する？（How） =====
個人開発環境を構築する
node.jsを使用できるようにする

### 受け入れ基準（期待すること）
- [ ] 個人開発環境を構築する
- [ ] node.jsを使用できる

**Comment by arith-alexander** [comment]
https://github.com/arith-y-ono/openId/pull/8 にて対応済み

**Comment by arith-y-ono** [comment]
完了したのでクローズします
