### ISSUE TITLE
ビルド環境にwebpackを実装する

### ISSUE THREAD

**Issue by arith-y-ono** [arith-y-ono/openId#7]
## ===== 期待する利益・回避したい不利益は？（Why）=====
https://github.com/arith-y-ono/openId/issues/1 参照

## ===== どうやって実現・解決する？（How） =====
amazonのecs環境にアップロードするときにwebpackを使用する

### 受け入れ基準（期待すること）
- [ ] amazonのecs環境にアップロードするときにwebpackを使用できる

**Comment by arith-alexander** [comment]
着手します

**Comment by arith-y-ono** [comment]
https://github.com/arith-y-ono/openId/pull/16
